name: Context testing
on: push

env:
  BRANCH_A: ${{ github.ref == 'refs/heads/a' }}
  BRANCH_B: ${{ github.ref == 'refs/heads/b' }}
  BRANCH_C: ${{ github.ref == 'refs/heads/c' }}

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        run: echo "A_OR_B=$($BRANCH_A == true || $BRANCH_B == true) ? true : false" >> $GITHUB_ENV
      - name: Dump environment
        run: echo $BRANCH_A $BRANCH_B $BRANCH_C
      - name: A Only Action
        run: echo 'We did it'
        if: env.BRANCH_A == 'true'
      - name: B Only Action
        run: echo 'We did it'
        if: env.BRANCH_B == 'true'
      - name: C Only Action
        run: echo 'We did it'
        if: env.BRANCH_C == 'true'
      - name: Everywhere but C action
        run: echo 'We did it'
        if: env.BRANCH_C == 'false'
      - name: A or B action
        run: echo 'We did it'
        if: env.A_OR_B == 'true'
